apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow
  namespace: mlops
spec:
  ingressClassName: traefik
  rules:
    - host: mlflow.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow
                port:
                  number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-api
  namespace: mlops
spec:
  ingressClassName: traefik
  rules:
    - host: mlops.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlops-api
                port:
                  number: 80
